// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1fyUH4-9MGaQFsR0WJWXMqCh0RIEDaqo',
    appId: '1:875128506039:web:2ba974fc34f6c299932f32',
    messagingSenderId: '875128506039',
    projectId: 'demoproject-a37ba',
    authDomain: 'demoproject-a37ba.firebaseapp.com',
    storageBucket: 'demoproject-a37ba.firebasestorage.app',
    measurementId: 'G-5E1RKCCC5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlUWkafZoc-1o4ieMFagAMWRxsWGXFt50',
    appId: '1:875128506039:android:dd147c072c2c1f67932f32',
    messagingSenderId: '875128506039',
    projectId: 'demoproject-a37ba',
    storageBucket: 'demoproject-a37ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTPGAAPSRjd65AuD-QJq1FF7wxlW5DSo',
    appId: '1:875128506039:ios:df43a6e1e01a028b932f32',
    messagingSenderId: '875128506039',
    projectId: 'demoproject-a37ba',
    storageBucket: 'demoproject-a37ba.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTPGAAPSRjd65AuD-QJq1FF7wxlW5DSo',
    appId: '1:875128506039:ios:df43a6e1e01a028b932f32',
    messagingSenderId: '875128506039',
    projectId: 'demoproject-a37ba',
    storageBucket: 'demoproject-a37ba.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1fyUH4-9MGaQFsR0WJWXMqCh0RIEDaqo',
    appId: '1:875128506039:web:7d25d6fb1b60807d932f32',
    messagingSenderId: '875128506039',
    projectId: 'demoproject-a37ba',
    authDomain: 'demoproject-a37ba.firebaseapp.com',
    storageBucket: 'demoproject-a37ba.firebasestorage.app',
    measurementId: 'G-C4J01BWVFY',
  );
}
